### ISSUE TITLE
Tech tree nodes seem backward - LaserDist200x and 500x come before 100x

### ISSUE THREAD

**Issue by Dunbaratu** [Dunbaratu/LaserDist#20]
It seems like in career you get access to the 100x model _after_ you got access to the 200x and 500x models already.  This isn't the way it's supposed to be.

**Comment by WazWaz** [comment]
For me, the 100x doesn't show up at all, I think because the cfg says:

`TechRequired = Advanced Electrics`

rather than:

`TechRequired = advElectrics`

**Comment by Dunbaratu** [comment]
Oldissue -no longer relevant as the tech names have changed in the Part.cfg files since then.
